[project]
name = "vanilla-qwen-inference"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "accelerate>=1.10.1",
    "qwen-vl-utils[decord]>=0.0.11",
    "transformers==4.51.3",
]
